const fs = require('fs');
const http = require('http');

const songs = [
    "Tu Hi Disda",
    "Shararat",
    "Gehra Hua",
    "Ram Ji Aake Bhala Karenge",
    "Ek Din",
    "Kya Bataun Tujhe",
    "Jaiye Sajana",
    "Bandhu 2.0",
    "Arz Kiya Hai",
    "Tujhko",
    "Saiyaara",
    "Hum Dono",
    "Sitaare",
    "Ban Ke Dikha",
    "Dhurandhar Title Track",
    "Tere Ishk Mein",
    "Aakhri Ishq",
    "Aaya Sher",
    "Chillgum",
    "Main Ishq Tera",
    "Har Subha Har Shaam",
    "Tu Meri Main Tera",
    "Yaa Rabba",
    "Tere Deewane",
    "Mann Hawa",
    "Pinjara",
    "Come On Baby",
    "Jab Talak",
    "Ghar Kab Aaoge",
    "Ishq Da Chehra",
    "Jaate Hue Lamhon",
    "Hindustan Meri Jaan",
    "Mitti Ke Bete",
    "Jee Liya",
    "Usey Kehna",
    "Bekasi",
    "Wild Ride",
    "Tamma Tamma",
    "Chand Dekh Lena",
    "Humne Wahin Lagaya Dil",
    "Akkad Bakkad",
    "Kaise Hua",
    "Heeriye",
    "Satranga",
    "O Maahi",
    "Pehle Bhi Main",
    "Chaleya",
    "Ve Kamleya",
    "Apna Bana Le",
    "Tere Vaaste",
    "Kesariya",
    "What Jhumka",
    "Tum Kya Mile",
    "Phir Aur Kya Chahiye",
    "Naina",
    "Aaj Ki Raat",
    "Taras",
    "Sajni",
    "Dekha Tenu",
    "Zaroor",
    "Ishq",
    "Millionaire",
    "Winning Speech",
    "Admirin You",
    "With You",
    "Softly",
    "Born To Shine",
    "Lover",
    "Excuses",
    "Brown Munde",
    "Insane",
    "True Stories",
    "Kinni Kinni",
    "Obsessed",
    "Cheques",
    "Still Rollin",
    "On Top",
    "Daku",
    "Players",
    "Wavy",
    "Old Money",
    "8 Asle",
    "California Love",
    "No Love",
    "Desires",
    "Husn",
    "Jo Tum Mere Ho",
    "Afsos",
    "Gul",
    "Baarishein",
    "Alag Aasmaan",
    "Kasoor",
    "Riha",
    "Mishri",
    "Iraaday",
    "Tu Hai Kahan",
    "Jhol",
    "Faasle",
    "Kabira",
    "Agar Tum Saath Ho",
    "Channa Mereya",
    "Ae Dil Hai Mushkil",
    "Raataan Lambiyan",
    "Ranjha",
    "Shayad",
    "Khairiyat",
    "Dil Diyan Gallan",
    "Tum Hi Ho",
    "Kaun Tujhe",
    "Janam Janam",
    "Gerua",
    "Soch Na Sake",
    "Tera Ban Jaunga",
    "Bekhayali",
    "Kaise Mujhe",
    "Agar Ho Tum",
    "Dil Bechara",
    "Apna Time Aayega",
    "Ilahi",
    "Safarnama",
    "Love You Zindagi",
    "Aabaad Barbaad",
    "Rait Zara Si",
    "Mast Magan",
    "Galliyan",
    "Sun Saathiya",
    "Samjhawan",
    "Bol Do Na Zara",
    "Main Rang Sharbaton Ka",
    "Tum Se Hi",
    "Iktara",
    "Tera Hone Laga Hoon",
    "Nazm Nazm",
    "Binte Dil",
    "Hawayein",
    "Muskurane",
    "Hamari Adhuri Kahani",
    "Sooraj Dooba Hain",
    "Dil Ko Karaar Aaya",
    "Maan Meri Jaan",
    "Tu Aake Dekhle",
    "Noor E Khuda",
    "Khuda Jaane",
    "Pee Loon",
    "Tum Mile",
    "Abhi Mujh Mein Kahin",
    "Saibo",
    "Phir Le Aaya Dil",
    "Tujhe Kitna Chahne Lage",
    "Tera Yaar Hoon Main",
    "Aayat",
    "Deva Deva",
    "Namo Namo",
    "Malang Sajna",
    "Rabba Janda",
    "Jhoome Jo Pathaan",
    "Besharam Rang",
    "Zinda Banda",
    "Not Ramaiya Vastavaiya",
    "Chammak Challo",
    "Ghungroo",
    "Nashe Si Chadh Gayi",
    "Kala Chashma",
    "Kar Gayi Chull",
    "Bom Diggy Diggy",
    "Morni Banke",
    "Param Sundari",
    "Tip Tip",
    "Dilbar",
    "Aankh Marey",
    "Gallan Goodiyaan",
    "London Thumakda",
    "Sweety Tera Drama",
    "Laal Peeli Akhiyaan",
    "Angaaron",
    "Pushpa Pushpa",
    "Kissik",
    "Srivalli",
    "Saami Saami",
    "Oo Antava",
    "Naatu Naatu",
    "Kesariya Tera",
    "Jee Ni Lagda",
    "Makhna",
    "Chogada",
    "Kamariya",
    "Akh Lad Jaave",
    "Coca Cola",
    "The Humma Song",
    "Dil Chori",
    "Naach Meri Rani",
    "Genda Phool",
    "Pachtaoge",
    "Filhaal",
    "Filhaal 2 Mohabbat",
    "Lut Gaye",
    "Meri Zindagi Hai Tu",
    "Barsaat Aa Gayi",
    "Kya Loge Tum",
    "Zihaal e Miskin",
    "O Sajna",
    "Mast Aankhein",
    "Raanjhana",
    "Chura Liya",
    "Baarish Ban Jaana",
    "Manike",
    "Tumhe Pyaar Karungga",
    "Dil Galti Kar Baitha",
    "Humnava Mere",
    "Mere Liye",
    "Rim Jhim",
    "Meri Banogi Kya",
    "Tu Mil Gaya",
    "Sajna Ve Sajna",
    "Tere Sang Yaara",
    "Jeene Laga Hoon",
    "Dil Ibaadat",
    "Piya O Re Piya",
    "Tum Tak",
    "Kun Faya Kun",
    "Arziyan",
    "Jashn-E-Bahaara"
];

const results = [];

const fetchSong = (query) => {
    return new Promise((resolve, reject) => {
        const url = `http://localhost:3000/api/songs?q=${encodeURIComponent(query)}&limit=1`;
        http.get(url, (res) => {
            let data = '';
            res.on('data', chunk => { data += chunk; });
            res.on('end', () => {
                try {
                    const parsed = JSON.parse(data);
                    if (parsed && parsed.length > 0) {
                        resolve(parsed[0]);
                    } else {
                        resolve(null);
                    }
                } catch (e) {
                    resolve(null);
                }
            });
        }).on('error', (err) => {
            resolve(null);
        });
    });
};

async function run() {
    console.log(`Starting to fetch ${songs.length} songs...`);
    for (let i = 0; i < songs.length; i++) {
        const query = songs[i];
        console.log(`[${i+1}/${songs.length}] Fetching: ${query}`);
        const result = await fetchSong(query);
        if (result) {
            results.push(result);
        } else {
            console.log(`Failed to find: ${query}`);
        }
        // Small delay to avoid overwhelming the local server
        await new Promise(r => setTimeout(r, 200));
    }

    fs.writeFileSync('src/assets/curated_hindi_songs.json', JSON.stringify(results, null, 2));
    console.log(`Saved ${results.length} songs to src/assets/curated_hindi_songs.json`);
}

run();
